import os

DATABASE = os.environ.get('SQLALCHEMY_DATABASE_URI')

class DevConfig:
    SQLALCHEMY_TRACK_MODIFICATIONS = os.environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
    SQLALCHEMY_DATABASE_URI = f"sqlite:///{DATABASE}"